openapi: 3.0.0
info:
  title: Scraping API Collection
  version: 1.0.0
  description: API Collection for Selenium Automation
servers:
  - url: http://localhost:3000
apis:
  - ./routers/*.js
tags:
  - name: Authentication
    description: Authentication Endpoints for B2C

paths:
  /b2c-authentication/sign-up:
    post:
      tags:
        - Authentication
      summary: Sign up for a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentName:
                  type: string
                schoolName:
                  type: string
                grade:
                  type: string
                state:
                  type: string
                country:
                  type: string
                email:
                  type: string
                password:
                  type: string

              example:
                studentName: Chirag
                schoolName: Don Bosco
                grade: 11
                state: New Delhi
                country: India
                email: chiragsharma1906@gmail.com
                password: Chirag@123

      responses:
        '200':
          description: Passed
          content:
            application/json:
              schema:
                type: object
                properties:
                  sucess:
                    type: string
              example:
                success: Passed Middleware...

  /b2c-authentication/verify:
    post:
      tags:
        - Authentication
      summary: Verify your existing user.
      parameters:
        - name: verificationId
          in: query
          description: verificationId found while sign-up
          required: true
          schema:
            type: string
      responses:
        202:
          description: Success

  /b2c-authentication/login:
    post:
      tags:
        - Authentication
      summary: Login with user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

              example:
                email: chiragsharma1906@gmail.com
                password: Chirag@123

      responses:
        200:
          description: Success

  /b2b-authentication/teacher-signup:
    post:
      tags:
        - Authentication
      summary: Create a new teacher account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teacherName:
                  type: string
                schoolName:
                  type: string
                grade:
                  type: string
                state:
                  type: string
                country:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                teacherName: TeacherX
                schoolName: Don Bosco
                grade: 11
                state: New Delhi
                country: India
                email: mr.x@donbosco.com
                password: Mr.x@12345
      responses:
        '201':
          description: Teacher created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  link:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /b2b-authentication/teacher-verify:
    post:
      tags:
        - Authentication
      summary: Verify teacher account
      parameters:
        - in: query
          name: verificationId
          schema:
            type: string
      responses:
        '202':
          description: Teacher verified
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /b2b-authentication/teacher-login:
    post:
      tags:
        - Authentication
      summary: Login as a teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: mr.x@donbosco.com
                password: Mr.x@12345
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /b2b-authentication/upload-students:
    post:
      tags:
        - Authentication
      summary: Upload student data in csv
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csvFile:
                  type: string
                  format: binary
                teacherId:
                  type: string

      responses:
        '200':
          description: Data uploaded
  # /b2b-authentication/student-signup:
  #   post:
  #     tags:
  #       - Authentication
  #     summary: Create a new student account
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #     responses:
  #       '201':
  #         description: Student created
  # Define other possible responses
  /b2b-authentication/student-verify:
    post:
      tags:
        - Authentication
      summary: Verify student account
      parameters:
        - in: query
          name: verificationId
          schema:
            type: string
      responses:
        '200':
          description: Student verified
        # Define other possible responses
  /b2b-authentication/student-login:
    post:
      tags:
        - Authentication
      summary: Login as a student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # Define properties for student login
      responses:
        '200':
          description: Successful login
        # Define other possible responses
